### ISSUE TITLE
Investigate Google Nearby API

### ISSUE THREAD

**Issue by wilsonpage** [mozilla-magnet/magnet#11]
When a beacon just transmits a UUID it may be associated with a record in 
Google's Nearby API. This record could contain rich metadata that we could display.

**Comment by wilsonpage** [comment]
Requests to 'Nearby' may require an app namespace, which may make this use-case redundant. Magnet want to know about all the beacons, not just ones relating to a particular app namespace.

**Comment by arcturus** [comment]
Namespaces are used for defining uuids, don't think is the use case for magnet. We won't need the eddystone uuid, but the eddystone url.
