### ISSUE TITLE
Check interactions with Google Forms and create Feedback form

### ISSUE THREAD

**Issue by samgiles** [mozilla-magnet/magnet#16]

**Comment by samgiles** [comment]
Interactions with Google Forms works in Android if you make it embed-able: https://tengam.org/oembed/?url=https%3A%2F%2Fdocs.google.com%2Fforms%2Fd%2F1AfMEbwmA2AbgK8SWaAyjNMqs3HmcOrX8TR25KcLeH0U%2Fviewform&width=400&height=400

We just need to create the form.

**Comment by wilsonpage** [comment]
@sgiles whats the status of this? Can you close if need be?

**Comment by samgiles** [comment]
Haven't been able to check iOS. That's all - everything else is done.

**Comment by samgiles** [comment]
It'll work in some form on iOS. Though.. So...
