### ISSUE TITLE
Whiteboard annoucements tile

### ISSUE THREAD

**Issue by wilsonpage** [mozilla-magnet/magnet#18]

**Comment by samgiles** [comment]
Did we decide on who would curate/what content would be curated on this?

**Comment by wilsonpage** [comment]
Off the top of my head: 
- Breakfast
- Lunch
- Evening activities

But the content is arbitrary, unforeseen use-cases may arise during the week.

**Comment by samgiles** [comment]
How does this look?  Arbitrary message + arbitrary (optional) attachment?

<img width="369" alt="screenshot 2016-06-07 18 10 13" src="https://cloud.githubusercontent.com/assets/840334/15867413/1af5583e-2cdb-11e6-8816-085080653f55.png">

Thinking of just hosting static pages on GitHub pages.

**Comment by wilsonpage** [comment]
Sweet! So the tile can just have any html in it?

**Comment by samgiles** [comment]
Yup

**Comment by samgiles** [comment]
Ok the repository is here: https://github.com/mozilla-magnet/london-announcements

Checkout, then copy the `template.html` file and update with content to create announcements.
