### ISSUE TITLE
Build photo-wall-client

### ISSUE THREAD

**Issue by wilsonpage** [mozilla-magnet/magnet#19]
Build the wwb app that displays the uplaoded photos.

**Comment by wilsonpage** [comment]
Pushed here https://github.com/mozilla-magnet/photo-wall-client. It should run on `gh-pages` fine, but needs the `service_url` configuring before. @samgiles where are we planning on hosting the photo-wall-service?

**Comment by samgiles** [comment]
@wilsonpage tengam.org I think, I'll deploy it.
