### ISSUE TITLE
Setup daily and weeky email reports

### ISSUE THREAD

**Issue by wilsonpage** [mozilla-magnet/magnet#28]
We need these reports flowing in to all core team members. Then we can start learning and tweaking the reports to surface the information we're interested in.

I'm currently running into [this bug](https://www.en.advertisercommunity.com/t5/Reports/Analytics-has-encountered-an-unexpected-condition-and-cannot/m-p/644064/highlight/false#M7942) which is preventing me from setting it up.

**Comment by isabelrios** [comment]
Hi @wilsonpage, I set the sent of the reports before going on holidays, I just checked it and you are not going to forgive me but... I did not add your email to the list :S sorry I forgot it! :( Just added it and starting today you should receive a daily and weekly (on Friday) report with data from project magnet app and also a weekly report (also on Friday) about project magnet site. Please let me know if you do not receive it yet.

**Comment by isabelrios** [comment]
This is closed, please reopen if there are more problems about receiving the reports.
Thanks!
