### ISSUE TITLE
Look for content for London virtual beacons

### ISSUE THREAD

**Issue by oteo** [mozilla-magnet/magnet#30]

**Comment by oteo** [comment]
I need to create a spreadsheet or document but in the meantime I am adding some links here:
From David [picture](https://drive.google.com/file/d/0B01m7pXAhdJmLVhBWXgxTmpndnc/view?usp=sharing):
http://www.walksoflondon.co.uk/
http://www.uncoveringlondon.co.uk/

Other links:
- Tour of the Beatles' London: http://www.freetoursbyfoot.com/tour-of-the-beatles-london/
- London's best street art: http://www.timeout.com/london/art/londons-best-street-art
- 26 Stunning Street Art Murals In East London: https://www.buzzfeed.com/danieldalton/stunning-street-art-murals-in-east-london?utm_term=.nmadQZgXx#.bhlnOK60z
- Interactive map: A street art tour of Shoreditch: 
- Top 20 public sculptures in London: http://www.timeout.com/london/art/top-20-public-sculptures-in-london
- The 50 best buildings in London: http://www.timeout.com/london/art/the-50-best-buildings-in-london#tab_panel_2

**Comment by wilsonpage** [comment]
Remember that the sites we link to must either have:
- A. URL/page per POI/beacon
- B. Hash anchor to target a specific part of the page (eg. `http://example.com/page1#item1`)

**Comment by wilsonpage** [comment]
- https://twitter.com/Rima1731
- https://twitter.com/The_East_End

**Comment by samgiles** [comment]
If this is collated in a csv file with each piece of content associated
with a "channel name", it should be pretty easy to write a script to import
straight into the database, I started hacking a `data-tool`, to help with this https://github.com/mozilla-magnet/magnet-services/blob/master/content-service/bin/data-tool.

Required fields are:

channel_name (string),
canonical_url (string),
call_to_action (JSON object as string - each key is a title, value the
URL),
extra_metadata (JSON object as string - any extra metadata to return from
the metadata server),
location_latitude (real number),
location_longitude (real number),

**Comment by oteo** [comment]
@samgiles I can try to put some of the info in the links in the format you suggest. Could you please provide an example, specially about the "call_to_action" and "extra_metadata" fields?

**Comment by dbialer** [comment]
I thought I would lay out a csv file with:
channel name, URL, name (of item - or is this extracted or one of the fields of the extra metadata?), Lat, Long, call to action (if any).
@samgiles Not sure what extra metadata would be?  Like name overide? (since titles of pages can be very long).
I would suggest some keywords or tags.  We may not use them, but if we add search or "related" content in the future, it may be helpful

That channels should have:
channel name, publisher name, short description.

**Comment by isabelrios** [comment]
A few more interesting places with content that could be helpful.
From freetoursbyfoot: 
Jack the riper: http://www.freetoursbyfoot.com/london-tours/walking-tours/jack-the-ripper-tour/

From strawberrytours: 
Jack the riper: https://strawberrytours.com/london/tours/free-jack-the-ripper-tour
Street art: https://strawberrytours.com/london/tours/free-street-art-graffiti-tour

London movie map (maybe we can get the locations and clips shown for each one): https://www.buzzfeed.com/lukelewis/london-movie-location-map?utm_term=.rxM9rVynKA#.nw182Q1bva

From walks.com:
Jack the riper: http://www.walks.com/popular-walks/jack-the-ripper-tour

London crime trail:
http://www.easyhiker.co.uk/themed-walks-london-crime-trail-part-1/
http://www.easyhiker.co.uk/themed-walks-london-crime-trail-part-2/

From London for free:
Jack the riper: http://www.londonforfree.net/walks/ripper-walk/

From free-london-tours.com:
http://free-london-tours.com/tours/free-original-london-alternative-tour/

I am a bit confused about how we are going to manage the content, the web sites I am finding have information in general about a theme, a particular movie for example, but there is not a different web page for POI related to that movie or a hash anchor. Not sure if they are valid so that we could get that specific information per POI. In any case having those web sites we could contant them in case we could do something together.

**Comment by oteo** [comment]
I've been talking to Francisco about the content of the  "call_to_action" and "extra_metadata" fields.

For "call_to_action" we should include a description of the possible actions user could take for an item as well as the URL for launching the action: 
`"{'Contact us': 'http://content_provider_URL/contact_us.html', 'Book a tour': 'http://content_provider_URL/bookings.html'}"`

For the "extra_metadata" field, the idea is that we could overwrite the information of the metadata server. This is an example of the tags managed by the metadata server:

```
{
        "title": "HM Prison Brixton",
        "description": "HM Prison Brixton is a local men's prison, located in Brixton area of the London Borough of Lambeth, in inner-South London. The prison is operated by Her Majesty's Prison Service.",
        "icon": "https://en.wikipedia.org/static/apple-touch/wikipedia.png",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Veiled_female_prisoner_at_the_Surrey_House_of_Correction_John_Johnson.jpg/220px-Veiled_female_prisoner_at_the_Surrey_House_of_Correction_John_Johnson.jpg",
        "keywords": [],
        "themeColor": "#ffffff",
        "siteName": "Wikipedia",
        "type": "Article",
        "url": "https://en.wikipedia.org/wiki/HM_Prison_Brixton",
        "id": "https://en.wikipedia.org/wiki/HM_Prison_Brixton",
        "unadaptedUrl": "https://en.wikipedia.org/wiki/HM_Prison_Brixton",
        "displayUrl": "https://en.wikipedia.org/wiki/HM_Prison_Brixton",
        "originalUrl": "https://en.wikipedia.org/wiki/HM_Prison_Brixton",
        "maxAge": 30000
    }
```

**Comment by wilsonpage** [comment]
Re @isabelrios's movie clips:
- 28 Days Later: https://www.youtube.com/watch?v=eCdRFMp8Xwo
- Bridge Jones: https://www.youtube.com/watch?v=gBvOHpNhswo
- Harry Potter:
  - https://youtu.be/Tc9nO3EuCh4
  - https://youtu.be/FArmRa092H0
  - Loads more here all linked to locations: http://londonist.com/2016/06/harry-potters-london

## 

If we do link directly to the YouTube clips, we may want to override the `description` with something better as YouTube descriptions are often pretty crappy eg: 'Bridget Jones's Diary (2001). Hugh Grant. Colin Firth. Fight scene #1', doesn't tell much of a story.

**Comment by wilsonpage** [comment]
- Lock Stock and Two Smocking Barrels: https://www.youtube.com/watch?v=wSodvRnD3Qc
- Notting Hill: https://www.youtube.com/watch?v=5nIxppYXonE
- James Bond SkyFall: https://www.youtube.com/watch?v=57Uy9jPxxwI

---

Quite a lot of clips aren't available on youtube, probably for copyright reasons.

**Comment by wilsonpage** [comment]
A series of short videos tied to locations to accompany a Jack the Ripper tour
https://www.jack-the-ripper-tour.com/videos/

**Comment by wilsonpage** [comment]
It seems if we can leverage YouTube content where-ever possible we have maximum 'candy' and guaranteed URL per piece of content.

**Comment by wilsonpage** [comment]
This is a great Twitter account for old London photographs: https://twitter.com/GreatestCapital

**Comment by wilsonpage** [comment]
London Transport Museum has some great content on Facebook: https://www.facebook.com/ltmuseum/

**Comment by wilsonpage** [comment]
![](https://scontent-lhr3-1.xx.fbcdn.net/t31.0-8/14481816_10154100620689353_1003411181243891555_o.jpg)

**Comment by wilsonpage** [comment]
Pinterest has plenty of curated lists, each item has it's own URL:
https://uk.pinterest.com/carolineh1145/history-picks/

**Comment by wilsonpage** [comment]
This article is GREAT:

https://www.buzzfeed.com/americanexpressuk/21-amazing-secret-places-to-find-in-london?utm_term=.qvWN672m6#.kcbw29b62

Not only does each item have an id/anchor, but they each have Google Maps link. We could ingest this easily.

**Comment by wilsonpage** [comment]
https://www.handpicked.org is an interesting site. They have curated lists of content from various sources. I haven't quite understood how it works yet. The homepage has no information or way to browse content. I think they perhaps use the site as real estate to forward people to from their various social media channels.

**Comment by wilsonpage** [comment]
From Handpicked.org: [London Oddities](https://www.handpicked.org/london_oddities)

**Comment by wilsonpage** [comment]
- Great content
- URL per item
- Needs lat/lon

http://www.telegraph.co.uk/travel/destinations/europe/united-kingdom/england/london/galleries/Londons-secret-sights-14-odd-attractions-you-never-knew-were-there/

**Comment by isabelrios** [comment]
Getting some POI from here: http://londonist.com/category/features/history
Some of them seem to be valid, url per POI with image.

**Comment by wilsonpage** [comment]
https://www.handpicked.org/1890_london

**Comment by wilsonpage** [comment]
Could we ingest this?
http://collage.cityoflondon.gov.uk/london-picture-map

**Comment by wilsonpage** [comment]
[AtlasObsura](http://www.atlasobscura.com) - Bloody Awesome!!

Here's a search near London: http://www.atlasobscura.com/search?utf8=%E2%9C%93&lat=51.5073509&lng=-0.12775829999998223&q=&formatted_address=&source=desktop&nearby=false
- Page per item
- Very rich metadata, they even have `og:latitude` and `og:longitude`!

**Comment by wilsonpage** [comment]
More info on OpenGraph Place metadata: https://developers.facebook.com/docs/reference/opengraph/object-type/place/

**Comment by wilsonpage** [comment]
https://www.instagram.com/derelictlondon/

**Comment by wilsonpage** [comment]
http://www.telegraph.co.uk/travel/destinations/europe/united-kingdom/england/london/galleries/Londons-secret-sights-16-more-odd-attractions-you-never-knew-were-there/

**Comment by wilsonpage** [comment]
https://www.instagram.com/p/gP6qQhs_zK/

**Comment by wilsonpage** [comment]
https://www.theguardian.com/travel/2015/jun/09/london-top-10-unusual-historical-sites

**Comment by oteo** [comment]
Francisco pointed me to this one
http://www.londonhistorygroup.com/
I have tried to broadcast one of the URL directly using Magnet-Desktop but in Magnet I can only see a blue tile and when I click on it, it says "Oops! That page can’t be found"

**Comment by wilsonpage** [comment]
Houman mentioned that if we had a spreadsheet that fed the magnet-service _anyone_ could contribute. We could ask people internally to help curate lists.

Content could be ingested from the spreadsheet(s) periodically. There are good APIs for accessing Google Spreadsheet data.

**Comment by wilsonpage** [comment]
Movie locations: https://www.buzzfeed.com/americanexpressuk/the-ultimate-movie-locations-tour-of-london?b=1&utm_term=.jx4QJ2EoJ#.tqXg6Np46

**Comment by wilsonpage** [comment]
Londonist has lots of nice vids/tours in specific locations across London https://www.youtube.com/user/Londonistvids
- [TFL Lost Property](https://www.youtube.com/watch?v=BT5so_HFW4s)
- [Series: Inside London](https://www.youtube.com/playlist?list=PLz1JuTRxlXhKrnQM8jFwTKJwP_KNjsFgZ)

**Comment by oteo** [comment]
http://www.visitacity.com/en/london/attraction-by-type/all
perhaps not very exacting topic, but it has content, picture and  a link for POI, and also a lot of locations

**Comment by oteo** [comment]
https://es.pinterest.com/anouchey/street-art-london/
nice pictures but I am missing content

**Comment by oteo** [comment]
Other sources provided by Wilson that we need to have a look (http://hidden-london.com/miscellany/london-websites/):
 http://hidden-london.com/
http://www.londonremembers.com/
http://londonmuralpreservationsociety.com/

**Comment by oteo** [comment]
Source pointed by David:
http://alondoninheritance.com/mapping-london-through-blog-posts/
