### ISSUE TITLE
Create a URL metadata validation tool

### ISSUE THREAD

**Issue by wilsonpage** [mozilla-magnet/magnet#34]
Right now the only way to really validate metadata is to render a tile in magnet-client. This is slow, especially when curating large content sets. 

As discussed in the today's standup, it would be nice to have a simple tool that runs a URL through the magnet-metadata-service and validates that output against a minimum requirement checklist:
- `title`
- `image`
- `description`
- `url`

This tool could just be a simple Github Pages page.

+@arcturus, @oteo, @samgiles, @isabelrios

**Comment by wilsonpage** [comment]
IMO this should be a pretty simple task.

**Comment by samgiles** [comment]
Maybe we could add a super simple browser based validator in a jsbin or
something if we set permissive cors headers, if not, a page on tengam.org,
either way you're right, this is simple.

I'll take this on.

**Comment by samgiles** [comment]
Couldn't sleep \o/, how's this? https://mozilla-magnet.github.io/metadata-tester/

**Comment by isabelrios** [comment]
Awesome! I tried with a couple of urls, ones that have all the metadata we need and other that was missing the image for example, and yeah it seems to detect everything if it is all there or something is missing! 
Will try with a few more but I thing it looks really good!

**Comment by wilsonpage** [comment]
Nice one @samgiles this will be very helpful!!

**Comment by oteo** [comment]
@samgiles @wilsonpage if now I need to create a specific content for a POI (e.g including coordinates and a picture) how could we verify that the data are fine or they can be seen properly in Magnet?
