### ISSUE TITLE
Look for content for Hawaii ww

### ISSUE THREAD

**Issue by oteo** [mozilla-magnet/magnet#54]

**Comment by isabelrios** [comment]
Found this general topics: 20 things you might not know about Hawaii
https://www.buzzfeed.com/mbvd/facts-you-might-not-know-about-hawaii?utm_term=.bryY2Zq7eb#.iewvmWlb71

**Comment by oteo** [comment]
Other sources that Francisco pointed to:
http://www.atlasobscura.com/things-to-do/hawaii 
http://www.unrealhawaii.com/
 https://www.flickr.com/groups//pool/map?&fLat=19.4393&fLon=-155.6748&zl=9&order_by=recent

Created Spreadsheetl for Hawaii Content in our Google Drive (https://docs.google.com/spreadsheets/d/1Zp8EFXI81WebkIwaqwwE_Thc7bSLnsXvyG6LZIs87Ak/edit?usp=sharing)

**Comment by isabelrios** [comment]
Missing geolocation, but there are separeted pages for each fact:
http://www.bigshocking.com/10-shocking-facts-hawaii-volcanoes-national-park/
http://www.bigshocking.com/10-shocking-facts-hawaii-volcanoes-national-park/2/
....

**Comment by isabelrios** [comment]
Just added to the doc file 14 POI from http://hawaiistateparks.org/parks/hawaii/
It is about 14 state parks that are in Hawaii
